version: '2'

#NETWORKING#################################################################
# By default Compose will set up a private network for the cluster #########
# Each container will join the network and can be reached by other #########
# containers at a host-name identical to the containres name.      #########
# It's necessary to keep the master container_name as 'master'     #########
# COMPOSE_PROJECT_NAME that is defined on .env file will also      #########
# determine the name of the network that spark nodes are running on.#########
# If that variable is not defined the network name will be         #########
# `{dir-name}_default`                                             #########
############################################################################

volumes:
  data:
    external: true    

services:
  worker:
    build: .
    command: ["/usr/bin/supervisord", "--configuration=/opt/conf/worker.conf"]
    environment:
      - PYSPARK_PYTHON=python3.6
      - PYSPARK_DRIVER_PYTHON=ipython
    volumes:
      - "data:/data"    
      